export const SORTING_VISUALIZER_ACTIONS = {
  SET_RANDOM_ARRAY: 'SET_RANDOM_ARRAY',

  // Sorting algorithms
  DO_NATIVE_SORT: 'DO_NATIVE_SORT',
  DO_MERGE_SORT_ARRAY: 'DO_MERGE_SORT_ARRAY',
  DO_BUBBLE_SORT_ARRAY: 'DO_BUBBLE_SORT_ARRAY',
};
